# Theme settings
theme: jekyll-theme-primer
markdown: kramdown

# Use the new layout
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

# Site settings
title: "Jarad DeLorenzo - Staff Engineer"
description: "Staff Engineer | Tech Innovator | AI Enthusiast"

# GitHub metadata
repository: delorenj/delorenj.github.io

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Enable kramdown GFM parser
kramdown:
  input: GFM
  syntax_highlighter: rouge